const items = [
    {
        id: "001",
        image: "images/shoes.webp",
        company: "ATOM",
        item_name: "Sneakers for Men",
        category: "Footwear",
        description: "Elevate your stride with these ultra-lightweight breathable sneakers. Designed with high-density foam cushioning for maximum impact absorption, they offer a perfect balance between athletic performance and street-ready style.",
        original_price: 2999,
        current_price: 1299,
        discount_percentage: 56,
        rating: { stars: 4.5, count: 1400 }
    },
    {
        id: "002",
        image: "images/toys.jpg",
        company: "FunToy",
        item_name: "Kids Toy Set",
        category: "Toys",
        description: "Spark imagination and creativity with this comprehensive multi-piece toy set. Made from non-toxic, child-safe materials, it is designed to help develop fine motor skills while providing hours of educational entertainment for growing minds.",
        original_price: 1199,
        current_price: 599,
        discount_percentage: 50,
        rating: { stars: 4.2, count: 800 }
    },
    {
        id: "003",
        image: "images/bag.jpg",
        company: "Skybags",
        item_name: "Travel Backpack",
        category: "Travel",
        description: "The ultimate companion for your adventures. This water-resistant backpack features ergonomically designed padded straps, a 15.6-inch dedicated laptop compartment, and multiple quick-access pockets for organized travel.",
        original_price: 3499,
        current_price: 1799,
        discount_percentage: 48,
        rating: { stars: 4.6, count: 2000 }
    },
    {
        id: "004",
        image: "images/mens.jpg",
        company: "Roadster",
        item_name: "Men Casual Shirt",
        category: "Clothing",
        description: "Crafted from 100% premium cotton, this slim-fit casual shirt offers a refined look without sacrificing comfort. Featuring a classic spread collar and button cuffs, it transitions seamlessly from office hours to evening gatherings.",
        original_price: 1999,
        current_price: 899,
        discount_percentage: 55,
        rating: { stars: 4.3, count: 1100 }
    },
    {
        id: "005",
        image: "images/women.jpg",
        company: "Zara",
        item_name: "Women Dress",
        category: "Clothing",
        description: "A statement piece from Zara's latest collection. This elegant dress features a flattering silhouette and breathable fabric, perfect for formal events or sophisticated evening wear. Designed to make you stand out with timeless grace.",
        original_price: 4999,
        current_price: 2499,
        discount_percentage: 50,
        rating: { stars: 4.7, count: 2500 }
    },
    {
        id: "006",
        image: "images/laptop.jpg",
        company: "HP",
        item_name: "Gaming Laptop",
        category: "Electronics",
        description: "Dominante the battlefield with high-performance hardware. This HP gaming rig features an advanced cooling system, a fast refresh rate display for tear-free gaming, and a backlit keyboard designed for precision and speed.",
        original_price: 89999,
        current_price: 65999,
        discount_percentage: 27,
        rating: { stars: 4.8, count: 3000 }
    },
    {
        id: "007",
        image: "images/perfume.avif",
        company: "Fogg",
        item_name: "Perfume Spray",
        category: "Beauty",
        description: "Stay fresh and confident all day long. Fogg's signature long-lasting fragrance is designed to withstand a busy lifestyle, offering a refreshing scent that leaves a bold impression without being overpowering.",
        original_price: 999,
        current_price: 499,
        discount_percentage: 50,
        rating: { stars: 4.4, count: 900 }
    },
    {
        id: "008",
        image: "images/phone.jpg",
        company: "Samsung",
        item_name: "Smartphone",
        category: "Electronics",
        description: "Experience the pinnacle of mobile technology. This Samsung device features a stunning AMOLED display, a pro-grade camera system for cinematic photography, and an all-day battery that keeps up with your every need.",
        original_price: 29999,
        current_price: 19999,
        discount_percentage: 33,
        rating: { stars: 4.6, count: 5000 }
    },
    {
        id: "009",
        image: "images/watch.jpg",
        company: "Fastrack",
        item_name: "Analog Watch",
        category: "Accessories",
        description: "Timekeeping meets urban style. This Fastrack analog watch features a durable mineral glass face, a comfortable leather strap, and precise quartz movement, making it the perfect accessory for the modern, style-conscious individual.",
        original_price: 2999,
        current_price: 1499,
        discount_percentage: 50,
        rating: { stars: 4.3, count: 2200 }
    },
    {
        id: "010",
        image: "images/head.jpg",
        company: "Boat",
        item_name: "Wireless Headphones",
        category: "Electronics",
        description: "Immerse yourself in high-fidelity sound. These Boat wireless headphones deliver deep, thumping bass and crystal-clear highs. With up to 20 hours of playtime, they are engineered for music lovers on the move.",
        original_price: 3999,
        current_price: 1999,
        discount_percentage: 50,
        rating: { stars: 4.5, count: 1800 }
    },
    {
        id: "011",
        image: "images/h&m.jpg",
        company: "H&M",
        item_name: "Cotton T-Shirt",
        category: "Clothing",
        description: "An essential staple for every wardrobe. This H&M T-shirt is made from sustainably sourced organic cotton, offering a soft-touch finish and a regular fit that stays comfortable throughout the day.",
        original_price: 1299,
        current_price: 599,
        discount_percentage: 54,
        rating: { stars: 4.3, count: 900 }
    },
    {
        id: "012",
        image: "images/levi.jpg",
        company: "Levi's",
        item_name: "Slim Fit Jeans",
        category: "Clothing",
        description: "The original denim icon. These Levi's slim-fit jeans are engineered with a hint of stretch for mobility and comfort. Featuring the classic five-pocket design and the iconic red tab, they are built to last a lifetime.",
        original_price: 3999,
        current_price: 2299,
        discount_percentage: 42,
        rating: { stars: 4.5, count: 1500 }
    },
    {
        id: "013",
        image: "images/glass.jpg",
        company: "RayBan",
        item_name: "Stylish Sunglasses",
        category: "Accessories",
        description: "Protect your eyes with legendary style. These RayBan sunglasses feature polarized lenses that reduce glare and provide 100% UV protection, all housed in a lightweight, high-quality frame that never goes out of fashion.",
        original_price: 2999,
        current_price: 1499,
        discount_percentage: 50,
        rating: { stars: 4.2, count: 700 }
    },
    {
        id: "014",
        image: "images/adidas.avif",
        company: "Adidas",
        item_name: "Sports Shoes",
        category: "Footwear",
        description: "Push your limits with Adidas performance. These sports shoes feature responsive cushioning and a grippy outsole for superior traction on both the track and the treadmill. Designed for athletes who demand the best.",
        original_price: 6499,
        current_price: 3299,
        discount_percentage: 49,
        rating: { stars: 4.6, count: 2000 }
    },
    {
        id: "015",
        image: "images/fab.jpg",
        company: "FabIndia",
        item_name: "Men Kurta Set",
        category: "Clothing",
        description: "Embrace tradition with modern elegance. This FabIndia kurta set is hand-crafted from breathable ethnic fabrics, featuring intricate detailing and a comfortable fit that is perfect for festive occasions and celebrations.",
        original_price: 3299,
        current_price: 1799,
        discount_percentage: 45,
        rating: { stars: 4.4, count: 1100 }
    },
    {
        id: "016",
        image: "images/lak.jpg",
        company: "Lakme",
        item_name: "Makeup Kit",
        category: "Beauty",
        description: "Your all-in-one beauty solution. This Lakme makeup kit includes essential high-pigment shades and professional tools to help you create stunning looks, from natural day-wear to glamourous evening makeup.",
        original_price: 1999,
        current_price: 999,
        discount_percentage: 50,
        rating: { stars: 4.7, count: 2300 }
    },
    {
        id: "017",
        image: "images/noise.avif",
        company: "Noise",
        item_name: "Smart Watch",
        category: "Electronics",
        description: "Track your health and stay connected. The Noise smart watch features a vivid touch display, heart rate monitoring, sleep tracking, and multiple sports modes to help you reach your fitness goals in style.",
        original_price: 4999,
        current_price: 2499,
        discount_percentage: 50,
        rating: { stars: 4.5, count: 3000 }
    }
];